--[[
    Drunken OS - File Manager Applet (v1.2)
    Modularized from drunken_os_apps.lua
]]

local files = {}
local appVersion = 1.3

local function getParent(context)
    return (context and context.parent) or context or {}
end

---
-- Gathers metadata for a file, such as size, type, and theme visual color.
-- @param path string: Directory path containing the file.
-- @param filename string: The name of the file to inspect.
-- @return table: File metdata object.
local function getFileInfo(path, filename, context)
    local fullPath = fs.combine(path, filename)
    local info = {
        name = filename,
        isDir = fs.isDir(fullPath),
        size = fs.getSize(fullPath),
        ext = filename:match("^.+(%.%w+)$") or ""
    }
    
    local theme = (context and context.theme) or {}
    if info.isDir then
        info.icon = ">"
        info.color = theme.prompt or colors.lightBlue
    elseif info.ext == ".lua" then
        if fullPath:match("games/") then
            info.icon = "*"
            info.color = theme.successText or colors.green
        else
            info.icon = "-"
            info.color = theme.warningText or colors.yellow
        end
    elseif info.ext == ".dat" or info.ext == ".db" or info.ext == ".json" then
        info.icon = "o"
        info.color = theme.linkText or colors.purple
    else
        info.icon = " "
        info.color = theme.text or colors.white
    end
    return info
end

---
-- Draws a modal to allow performing actions (run, sync, etc) on a selected file.
-- @param context table: OS environment context.
-- @param file table: Metadata object generated by getFileInfo.
-- @param isCloud boolean: Flag to determine if modal is viewing cloud storage.
function files.fileActionModal(context, file, isCloud)
    local options = {}
    if not file.isDir then
        if not isCloud and file.ext == ".lua" then table.insert(options, "[>] Run") end
        if not isCloud then table.insert(options, "[^] Sync to Cloud") end
        if isCloud then table.insert(options, "[v] Download Local") end
        table.insert(options, "[@] Mail to...")
        if not isCloud then table.insert(options, "[~] Beam (AirDrop)") end
    end
    table.insert(options, "[X] Delete")
    table.insert(options, "Cancel")

    local selected = 1
    while true do
        context.drawWindow(file.name)
        local w, h = context.getSafeSize()
        term.setCursorPos(2, 4); term.setTextColor(context.theme.mutedText or colors.gray)
        term.write(string.format("Type: %s | Size: %d b", file.isDir and "Folder" or (file.ext ~= "" and file.ext or "File"), file.size))
        
        context.drawMenu(options, selected, 2, 6)
        local event, p1, p2, p3 = os.pullEvent()
        if event == "key" then
            local key = p1
            if key == keys.up then selected = (selected == 1) and #options or selected - 1
            elseif key == keys.down then selected = (selected == #options) and 1 or selected + 1
            elseif key == keys.enter then break
            elseif key == keys.tab or key == keys.q then break end
        elseif event == "mouse_click" then
            local btn, clickX, clickY = p1, p2, p3
            local clickedIdx = clickY - 6 + 1
            if clickedIdx >= 1 and clickedIdx <= #options then
                selected = clickedIdx
                break
            end
        elseif event == "mouse_scroll" then
            local dir = p1
            if dir < 0 then selected = (selected == 1) and #options or selected - 1
            else selected = (selected == #options) and 1 or selected + 1 end
        end
    end

    local choice = options[selected]
    return (choice ~= "Cancel") and choice or nil
end

---
-- Main application entry point for the universal File Manager.
-- Controls local filesystem navigation and Mainframe Cloud file syncing.
-- @param context table: The OS environment context.
function files.run(context)
    local currentPath = ""
    local storageMode = "Local"
    local selected = 1
    local scroll = 1
    local cloudFiles = {}

    local function refreshCloud()
        context.drawWindow("Syncing...")
        rednet.send(getParent(context).mailServerId, { type = "list_cloud", user = getParent(context).username, session_token = getParent(context).session_token }, "SimpleMail")
        local _, response = rednet.receive("SimpleMail", 5)
        if response and response.files then
            cloudFiles = response.files
            for i, f in ipairs(cloudFiles) do
                f.ext = f.name:match("^.+(%.%w+)$") or ""
                f.icon = f.isDir and ">" or "-"
                f.color = f.isDir and (context.theme.prompt or colors.lightBlue) or (context.theme.text or colors.white)
            end
        else
            context.showMessage("Error", "Cloud Offline"); storageMode = "Local"
        end
    end

    while true do
        local files = {}
        if storageMode == "Local" then
            local rawFiles = fs.list(currentPath)
            table.sort(rawFiles)
            if currentPath ~= "" then table.insert(files, { name = "..", isDir = true, icon = "<", color = context.theme.mutedText or colors.gray }) end
            for _, f in ipairs(rawFiles) do table.insert(files, getFileInfo(currentPath, f, context)) end
        else
            files = cloudFiles
            if #files == 0 then table.insert(files, { name = "(Cloud Empty)", icon = " ", color = context.theme.mutedText or colors.gray, disabled = true }) end
        end

        context.drawWindow("Files: " .. storageMode)
        local w, h = context.getSafeSize()
        term.setCursorPos(2, 2); term.setTextColor(storageMode == "Local" and (context.theme.text or colors.white) or (context.theme.mutedText or colors.gray)); term.write("[Local]")
        term.setCursorPos(10, 2); term.setTextColor(storageMode == "Cloud" and (context.theme.text or colors.white) or (context.theme.mutedText or colors.gray)); term.write("[Cloud]")
        term.setCursorPos(2, 3); term.setTextColor(context.theme.prompt or colors.cyan); term.write("/" .. currentPath)
        
        local listHeight = h - 5
        selected = math.max(1, math.min(selected, #files))
        if selected < scroll then scroll = selected end
        if selected >= scroll + listHeight then scroll = selected - listHeight + 1 end

        for i = scroll, math.min(scroll + listHeight - 1, #files) do
            local f = files[i]
            term.setCursorPos(2, 4 + (i - scroll))
            if i == selected then term.setBackgroundColor(context.theme.highlightBg); term.setTextColor(context.theme.highlightText)
            else term.setBackgroundColor(context.theme.bg); term.setTextColor(f.color) end
            term.write(string.format(" %s %s", f.icon, f.name))
            term.setBackgroundColor(context.theme.bg)
        end

        term.setCursorPos(2, h - 1)
        term.setTextColor(context.theme.mutedText or colors.gray)
        term.write("[R] AirDrop In  [Enter] Options")

        local event, p1, p2, p3 = os.pullEvent()
        local key = nil
        if event == "key" then
            key = p1
            if key == keys.up then selected = selected - 1
            elseif key == keys.down then selected = selected + 1
            elseif key == keys.left or key == keys.right then
                storageMode = (storageMode == "Local") and "Cloud" or "Local"
                if storageMode == "Cloud" then refreshCloud() end
                selected = 1; scroll = 1
            end
        elseif event == "mouse_click" then
            local btn, clickX, clickY = p1, p2, p3
            if clickY == 2 then
                if clickX >= 2 and clickX <= 8 then
                    if storageMode ~= "Local" then
                        storageMode = "Local"
                        selected = 1; scroll = 1
                    end
                elseif clickX >= 10 and clickX <= 17 then
                    if storageMode ~= "Cloud" then
                        storageMode = "Cloud"
                        refreshCloud()
                        selected = 1; scroll = 1
                    end
                end
            elseif clickY >= 4 and clickY <= 4 + listHeight - 1 then
                local clickedRow = scroll + (clickY - 4)
                if clickedRow >= 1 and clickedRow <= #files then
                    selected = clickedRow
                    key = keys.enter
                end
            end
        elseif event == "mouse_scroll" then
            local dir = p1
            if dir < 0 then selected = selected - 1
            else selected = selected + 1 end
        end

        if key == keys.enter then
            local f = files[selected]
            if f and not f.disabled then
                if f.isDir then
                    currentPath = (f.name == "..") and fs.getDir(currentPath) or fs.combine(currentPath, f.name)
                    selected = 1; scroll = 1
                else
                    local action = files.fileActionModal(context, f, storageMode == "Cloud")
                    if action == "[>] Run" then
                        context.clear()
                        local run_shell = context.shell or _G.shell
                        if run_shell and run_shell.run then
                            run_shell.run(fs.combine(currentPath, f.name))
                        else
                            context.showMessage("Error", "Shell API unavailable.")
                        end
                        context.showMessage("Exited", "Finished.")
                    elseif action == "[^] Sync to Cloud" then
                        local file = fs.open(fs.combine(currentPath, f.name), "r")
                        local content = file.readAll(); file.close()
                        rednet.send(getParent(context).mailServerId, { type = "sync_file", user = getParent(context).username, filename = f.name, content = content, session_token = getParent(context).session_token }, "SimpleMail")
                        local _, resp = rednet.receive("SimpleMail", 5); context.showMessage("Sync", (resp and resp.success) and "Uploaded!" or "Failed")
                    elseif action == "[v] Download Local" then
                        rednet.send(getParent(context).mailServerId, { type = "download_cloud", user = getParent(context).username, filename = f.name, session_token = getParent(context).session_token }, "SimpleMail")
                        local _, resp = rednet.receive("SimpleMail", 10)
                        if resp and resp.success then
                            local file = fs.open(fs.combine(currentPath, f.name), "w")
                            file.write(resp.content); file.close(); context.showMessage("Sync", "Downloaded!")
                        end
                    elseif action == "[@] Mail to..." then
                        local to = context.readInput("To: ", h - 1)
                        if to and to ~= "" then
                            local content
                            if storageMode == "Cloud" then
                                rednet.send(getParent(context).mailServerId, { type = "download_cloud", user = getParent(context).username, filename = f.name, session_token = getParent(context).session_token }, "SimpleMail")
                                local _, resp = rednet.receive("SimpleMail", 5); content = resp and resp.content
                            else
                                local file = fs.open(fs.combine(currentPath, f.name), "r"); content = file.readAll(); file.close()
                            end
                            if content then
                                local mailObj = { from = getParent(context).username, from_nickname = getParent(context).nickname, to = to, subject = "Shared File: " .. f.name, body = "Attached: " .. f.name, timestamp = os.time(), attachment = { name = f.name, content = content } }
                                rednet.send(getParent(context).mailServerId, { type = "send", mail = mailObj, session_token = getParent(context).session_token, user = getParent(context).username }, "SimpleMail")
                                context.showMessage("Mail", "Sent!")
                            end
                        end
                    elseif action == "[~] Beam (AirDrop)" then
                        local transfer = require("lib.transfer")
                        if not rednet.isOpen() then
                            local m = peripheral.find("modem")
                            if m then rednet.open(peripheral.getName(m)) end
                        end
                        context.drawWindow("AirDrop - Pinging...")
                        term.setCursorPos(2, 4); term.setTextColor(context.theme.prompt or colors.yellow)
                        term.write("Scanning for nearby devices...")
                        
                        rednet.broadcast({ type = "airdrop_ping", user = getParent(context).username }, "DrunkenAirDrop")
                        local devices = {}
                        local scanTimer = os.startTimer(1.0)
                        while true do
                            local ev, p1, p2, p3 = os.pullEvent()
                            if ev == "timer" and p1 == scanTimer then break
                            elseif ev == "rednet_message" and p3 == "DrunkenAirDrop" and type(p2) == "table" and p2.type == "airdrop_pong" then
                                table.insert(devices, { id = p1, name = p2.user or ("Device " .. p1) })
                            end
                        end
                        
                        local targetId = nil
                        if #devices == 0 then
                            context.drawWindow("AirDrop Target")
                            term.setCursorPos(2, 4); term.setTextColor(colors.yellow)
                            term.write("No beacon found. Enter Computer ID:")
                            local idStr = context.readInput("Target ID: ", 6)
                            targetId = tonumber(idStr)
                        else
                            local devNames = {}
                            for _, d in ipairs(devices) do table.insert(devNames, string.format("[%d] %s", d.id, d.name)) end
                            table.insert(devNames, "Enter Custom ID")
                            local pick = context.drawMenu(devNames, 1, 2, 5)
                            if pick <= #devices then
                                targetId = devices[pick].id
                            else
                                local idStr = context.readInput("Target ID: ", 6)
                                targetId = tonumber(idStr)
                            end
                        end
                        
                        if targetId then
                            local fullP = fs.combine(currentPath, f.name)
                            local fp = fs.open(fullP, "r")
                            local data = fp.readAll()
                            fp.close()
                            
                            context.drawWindow("AirDrop Streaming")
                            term.setCursorPos(2, 4); term.setTextColor(context.theme.prompt or colors.yellow)
                            term.write("Beaming: " .. f.name)
                            
                            local success, err = transfer.sendStreaming(targetId, f.name, data, "DrunkenAirDrop", function(sent, total, idx, totChunks)
                                local pct = math.floor((sent / total) * 100)
                                term.setCursorPos(2, 6); term.setTextColor(context.theme.prompt or colors.yellow)
                                term.write(string.format("Progress: %d%% (%d/%d B)", pct, sent, total))
                                local barLen = math.min(18, math.floor(pct / 6))
                                term.setCursorPos(2, 7)
                                term.write("[" .. string.rep("=", barLen) .. string.rep(" ", 18 - barLen) .. "]")
                            end)
                            
                            if success then
                                context.showMessage("AirDrop", "File beamed successfully!")
                            else
                                context.showMessage("AirDrop Failed", err or "Transmission timed out.")
                            end
                        end
                    elseif action == "[X] Delete" then
                        if storageMode == "Local" then fs.delete(fs.combine(currentPath, f.name))
                        else rednet.send(getParent(context).mailServerId, { type = "delete_cloud", user = getParent(context).username, filename = f.name, session_token = getParent(context).session_token }, "SimpleMail")
                             rednet.receive("SimpleMail", 2); refreshCloud() end
                    end
                end
            end
        elseif key == keys.r and storageMode == "Local" then
            -- AirDrop Receiver Mode
            local transfer = require("lib.transfer")
            if not rednet.isOpen() then
                local m = peripheral.find("modem")
                if m then rednet.open(peripheral.getName(m)) end
            end
            context.drawWindow("AirDrop Receiver")
            term.setCursorPos(2, 4); term.setTextColor(context.theme.prompt or colors.yellow)
            term.write("Listening for incoming beam...")
            term.setCursorPos(2, 6); term.setTextColor(context.theme.mutedText or colors.gray)
            term.write("Ready to receive files.")
            term.setCursorPos(2, h - 1); term.write("Press [Q] to cancel.")
            
            local completedName, completedData = nil, nil
            local receiver = transfer.createReceiver(
                function(data, filename, senderId)
                    completedName = filename
                    completedData = data
                end,
                function(bytes, total, idx, totalChunks)
                    term.setCursorPos(2, 8); term.setTextColor(colors.lime)
                    term.write(string.format("Receiving: %d/%d bytes...", bytes, total))
                end
            )
            
            while not completedName do
                local ev, p1, p2, p3 = os.pullEvent()
                if ev == "key" and p1 == keys.q then break
                elseif ev == "rednet_message" and p3 == "DrunkenAirDrop" then
                    if type(p2) == "table" and p2.type == "airdrop_ping" then
                        rednet.send(p1, { type = "airdrop_pong", user = getParent(context).username }, "DrunkenAirDrop")
                    else
                        receiver.handleMessage(p1, p2, p3)
                    end
                end
            end
            
            if completedName and completedData then
                local savePath = fs.combine(currentPath, completedName)
                local fp = fs.open(savePath, "w")
                if fp then
                    fp.write(completedData)
                    fp.close()
                    context.showMessage("AirDrop Received", "Saved: " .. completedName)
                end
            end
        elseif key == keys.tab or key == keys.q then break end
    end
end

return files
